/* Tests the extended tool set. Open http://localhost:5191/ while it runs. */
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const srv = spawn(process.execPath, [join(dirname(fileURLToPath(import.meta.url)), 'server.mjs')], { stdio: ['pipe', 'pipe', 'inherit'] });
let buf = '', nid = 1; const pend = new Map();
srv.stdout.on('data', d => { buf += d; let i; while ((i = buf.indexOf('\n')) >= 0) { const m = JSON.parse(buf.slice(0, i)); buf = buf.slice(i + 1); pend.get(m.id)?.(m); } });
const rpc = (method, params) => new Promise(r => { const id = nid++; pend.set(id, r); srv.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n'); });
const call = async (name, args = {}) => { const m = await rpc('tools/call', { name, arguments: args }); const t = m.result.content[0].text; let j; try { j = JSON.parse(t); } catch (e) { j = t; } return m.result.isError ? 'ERR ' + t : j; };
const show = (label, v, n = 300) => console.log(label.padEnd(22), (typeof v === 'string' ? v : JSON.stringify(v)).slice(0, n));
await rpc('initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'test', version: '1' } });
console.log('tools:', (await rpc('tools/list', {})).result.tools.length);
for (let i = 0; i < 30; i++) { const s = await call('state_brief'); if (typeof s === 'object') break; await new Promise(r => setTimeout(r, 2000)); }
await call('new_game', { name: 'Test AI', seed: 'mcp2', mode: 'normal' });
show('state_brief', await call('state_brief'));
show('orders', await call('orders'));
show('sell ryby 3', await call('sell', { item: 'ryby', amount: 3 }));
show('storage_rules', await call('storage_rules', { rules: { psenice: { sell_excess_over: 20 }, chleb: { reserve: 6 } } }));
show('list_deposits', await call('list_deposits'));
show('find_resource kamen', await call('find_resource', { resource: 'kamen' }));
const spot = (await call('find_spot', { type: 'mlyn' })).spots[0];
show('batch', await call('batch', { commands: [{ tool: 'build', type: 'mlyn', ...spot }, { tool: 'build', type: 'nesmysl', x: 0, y: 0 }, { tool: 'auto_assign' }] }), 400);
show('construction_status', await call('construction_status'));
show('dry_run', await call('dry_run', { commands: [{ tool: 'build_many', type: 'kvetiny', count: 3 }], then_hours: 6 }));
show('checkpoint save', await call('checkpoint', { action: 'save', name: 'pred' }));
show('skip_time 12h', await call('skip_time', { game_hours: 12, stop_on: ['construction_done'] }));
show('simulate_until', await call('simulate_until', { condition: 'built.mlyn >= 1', max_game_days: 3 }));
show('production_status', await call('production_status'));
show('simulate_preview', await call('simulate_preview', { game_days: 2 }));
show('fast_forward', await call('fast_forward_report', { game_days: 1, interval_hours: 8 }), 500);
show('rules add', await call('rules', { action: 'add', condition: 'storage_used_pct > 80', then: [{ tool: 'sell', item: 'psenice', excess_over: 10 }] }));
show('notes add', await call('notes', { action: 'add', text: 'Kámen je na severu', tags: ['mining'] }));
show('notes list', await call('notes', { action: 'list' }));
show('events', await call('events', { since: 0 }), 400);
show('recommend', await call('recommend_next_actions'), 400);
show('checkpoint restore', await call('checkpoint', { action: 'restore', name: 'pred' }));
show('ensure_running', await call('ensure_running', { speed: 2 }));
show('bad condition', await call('simulate_until', { condition: 'rm -rf / > 1' }));
show('action_catalog', (await call('action_catalog')).length + ' actions');
srv.kill(); process.exit(0);
